//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralid.Attendance.Model {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ralid.Attendance.Model.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自助缴费机纸币识别机警报 的本地化字符串。
        /// </summary>
        internal static string AlarmType_APMBillValidator {
            get {
                return ResourceManager.GetString("AlarmType_APMBillValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自助缴费机读卡器警报 的本地化字符串。
        /// </summary>
        internal static string AlarmType_APMCardReader {
            get {
                return ResourceManager.GetString("AlarmType_APMCardReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自助缴费机硬币找零机警报 的本地化字符串。
        /// </summary>
        internal static string AlarmType_APMCoinCharger {
            get {
                return ResourceManager.GetString("AlarmType_APMCoinCharger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自助缴费机密码键盘警报 的本地化字符串。
        /// </summary>
        internal static string AlarmType_APMKeyboard {
            get {
                return ResourceManager.GetString("AlarmType_APMKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自助缴费机打印机警报 的本地化字符串。
        /// </summary>
        internal static string AlarmType_APMPrinter {
            get {
                return ResourceManager.GetString("AlarmType_APMPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自助缴费机系统警报 的本地化字符串。
        /// </summary>
        internal static string AlarmType_APMSystem {
            get {
                return ResourceManager.GetString("AlarmType_APMSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消收费 的本地化字符串。
        /// </summary>
        internal static string AlarmType_CancelCardPayment {
            get {
                return ResourceManager.GetString("AlarmType_CancelCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆到达 的本地化字符串。
        /// </summary>
        internal static string AlarmType_CarArrive {
            get {
                return ResourceManager.GetString("AlarmType_CarArrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆离开 的本地化字符串。
        /// </summary>
        internal static string AlarmType_CarLeave {
            get {
                return ResourceManager.GetString("AlarmType_CarLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工落闸 的本地化字符串。
        /// </summary>
        internal static string AlarmType_Closedoor {
            get {
                return ResourceManager.GetString("AlarmType_Closedoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效卡片 的本地化字符串。
        /// </summary>
        internal static string AlarmType_InvalidCard {
            get {
                return ResourceManager.GetString("AlarmType_InvalidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改收费记录 的本地化字符串。
        /// </summary>
        internal static string AlarmType_ModifyCardPayment {
            get {
                return ResourceManager.GetString("AlarmType_ModifyCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人工抬闸 的本地化字符串。
        /// </summary>
        internal static string AlarmType_Opendoor {
            get {
                return ResourceManager.GetString("AlarmType_Opendoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员登录 的本地化字符串。
        /// </summary>
        internal static string AlarmType_OperatorLogIn {
            get {
                return ResourceManager.GetString("AlarmType_OperatorLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸票打印机状态 的本地化字符串。
        /// </summary>
        internal static string AlarmType_PrinterStatus {
            get {
                return ResourceManager.GetString("AlarmType_PrinterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string APMLogType_Alarm {
            get {
                return ResourceManager.GetString("APMLogType_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string APMLogType_Error {
            get {
                return ResourceManager.GetString("APMLogType_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string APMLogType_Message {
            get {
                return ResourceManager.GetString("APMLogType_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸币识别机故障 的本地化字符串。
        /// </summary>
        internal static string APMStatus_BillValidatorFault {
            get {
                return ResourceManager.GetString("APMStatus_BillValidatorFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱箱已满 的本地化字符串。
        /// </summary>
        internal static string APMStatus_CashBoxFull {
            get {
                return ResourceManager.GetString("APMStatus_CashBoxFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬币找零器故障 的本地化字符串。
        /// </summary>
        internal static string APMStatus_CoinChangerFault {
            get {
                return ResourceManager.GetString("APMStatus_CoinChangerFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬币数量不足 的本地化字符串。
        /// </summary>
        internal static string APMStatus_CoinShortage {
            get {
                return ResourceManager.GetString("APMStatus_CoinShortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地数据库故障 的本地化字符串。
        /// </summary>
        internal static string APMStatus_LocalDBFault {
            get {
                return ResourceManager.GetString("APMStatus_LocalDBFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录停车场服务器失败 的本地化字符串。
        /// </summary>
        internal static string APMStatus_LoginParkingFault {
            get {
                return ResourceManager.GetString("APMStatus_LoginParkingFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金属小键盘故障 的本地化字符串。
        /// </summary>
        internal static string APMStatus_MetalKeyboardFault {
            get {
                return ResourceManager.GetString("APMStatus_MetalKeyboardFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string APMStatus_Normal {
            get {
                return ResourceManager.GetString("APMStatus_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停车场连接故障 的本地化字符串。
        /// </summary>
        internal static string APMStatus_ParkingConnectedFault {
            get {
                return ResourceManager.GetString("APMStatus_ParkingConnectedFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机故障 的本地化字符串。
        /// </summary>
        internal static string APMStatus_PrinterFault {
            get {
                return ResourceManager.GetString("APMStatus_PrinterFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机缺纸 的本地化字符串。
        /// </summary>
        internal static string APMStatus_PrinterPaperAbsent {
            get {
                return ResourceManager.GetString("APMStatus_PrinterPaperAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读卡器故障 的本地化字符串。
        /// </summary>
        internal static string APMStatus_ReaderFault {
            get {
                return ResourceManager.GetString("APMStatus_ReaderFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取到的卡片数据错误！ 的本地化字符串。
        /// </summary>
        internal static string CardOperationManager_CardDataError {
            get {
                return ResourceManager.GetString("CardOperationManager_CardDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片ID号不符！ 的本地化字符串。
        /// </summary>
        internal static string CardOperationManager_CardIDError {
            get {
                return ResourceManager.GetString("CardOperationManager_CardIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片不是有效卡片！ 的本地化字符串。
        /// </summary>
        internal static string CardOperationManager_CardInvalid {
            get {
                return ResourceManager.GetString("CardOperationManager_CardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化卡片密钥失败! 的本地化字符串。
        /// </summary>
        internal static string CardOperationManager_InitKeyFail {
            get {
                return ResourceManager.GetString("CardOperationManager_InitKeyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有卡片！ 的本地化字符串。
        /// </summary>
        internal static string CardOperationManager_NoCard {
            get {
                return ResourceManager.GetString("CardOperationManager_NoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能读到卡片数据！ 的本地化字符串。
        /// </summary>
        internal static string CardOperationManager_NoCardData {
            get {
                return ResourceManager.GetString("CardOperationManager_NoCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取到的卡片不是当前操作的卡片！ 的本地化字符串。
        /// </summary>
        internal static string CardOperationManager_NoCurrentCard {
            get {
                return ResourceManager.GetString("CardOperationManager_NoCurrentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除 的本地化字符串。
        /// </summary>
        internal static string CardStatus_Deleted {
            get {
                return ResourceManager.GetString("CardStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string CardStatus_Disabled {
            get {
                return ResourceManager.GetString("CardStatus_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发行 的本地化字符串。
        /// </summary>
        internal static string CardStatus_Enabled {
            get {
                return ResourceManager.GetString("CardStatus_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂失 的本地化字符串。
        /// </summary>
        internal static string CardStatus_Loss {
            get {
                return ResourceManager.GetString("CardStatus_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string CardStatus_Recycled {
            get {
                return ResourceManager.GetString("CardStatus_Recycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日租卡 的本地化字符串。
        /// </summary>
        internal static string CardType_DayRentCard {
            get {
                return ResourceManager.GetString("CardType_DayRentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理卡 的本地化字符串。
        /// </summary>
        internal static string CardType_ManagedCard {
            get {
                return ResourceManager.GetString("CardType_ManagedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总监卡 的本地化字符串。
        /// </summary>
        internal static string CardType_MonitorCard {
            get {
                return ResourceManager.GetString("CardType_MonitorCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月租卡 的本地化字符串。
        /// </summary>
        internal static string CardType_MonthRentCard {
            get {
                return ResourceManager.GetString("CardType_MonthRentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员卡 的本地化字符串。
        /// </summary>
        internal static string CardType_OperatorCard {
            get {
                return ResourceManager.GetString("CardType_OperatorCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它卡 的本地化字符串。
        /// </summary>
        internal static string CardType_Other {
            get {
                return ResourceManager.GetString("CardType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业主卡 的本地化字符串。
        /// </summary>
        internal static string CardType_OwnerCard {
            get {
                return ResourceManager.GetString("CardType_OwnerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 储值卡 的本地化字符串。
        /// </summary>
        internal static string CardType_PrepayCard {
            get {
                return ResourceManager.GetString("CardType_PrepayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深圳通 的本地化字符串。
        /// </summary>
        internal static string CardType_ShenZhen {
            get {
                return ResourceManager.GetString("CardType_ShenZhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时卡 的本地化字符串。
        /// </summary>
        internal static string CardType_TempCard {
            get {
                return ResourceManager.GetString("CardType_TempCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试卡 的本地化字符串。
        /// </summary>
        internal static string CardType_TestCard {
            get {
                return ResourceManager.GetString("CardType_TestCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸票 的本地化字符串。
        /// </summary>
        internal static string CardType_Ticket {
            get {
                return ResourceManager.GetString("CardType_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义卡片1 的本地化字符串。
        /// </summary>
        internal static string CardType_UserDefinedCard1 {
            get {
                return ResourceManager.GetString("CardType_UserDefinedCard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义卡片2 的本地化字符串。
        /// </summary>
        internal static string CardType_UserDefinedCard2 {
            get {
                return ResourceManager.GetString("CardType_UserDefinedCard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP卡 的本地化字符串。
        /// </summary>
        internal static string CardType_VipCard {
            get {
                return ResourceManager.GetString("CardType_VipCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 羊城通 的本地化字符串。
        /// </summary>
        internal static string CardType_YangCheng {
            get {
                return ResourceManager.GetString("CardType_YangCheng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中山通卡 的本地化字符串。
        /// </summary>
        internal static string CardType_Zhongshan {
            get {
                return ResourceManager.GetString("CardType_Zhongshan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A型车 的本地化字符串。
        /// </summary>
        internal static string CarType_A {
            get {
                return ResourceManager.GetString("CarType_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B型车 的本地化字符串。
        /// </summary>
        internal static string CarType_B {
            get {
                return ResourceManager.GetString("CarType_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C型车 的本地化字符串。
        /// </summary>
        internal static string CarType_C {
            get {
                return ResourceManager.GetString("CarType_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小型车 的本地化字符串。
        /// </summary>
        internal static string CarType_Car {
            get {
                return ResourceManager.GetString("CarType_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D型车 的本地化字符串。
        /// </summary>
        internal static string CarType_D {
            get {
                return ResourceManager.GetString("CarType_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摩托车 的本地化字符串。
        /// </summary>
        internal static string CarType_Motor {
            get {
                return ResourceManager.GetString("CarType_Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超大型车 的本地化字符串。
        /// </summary>
        internal static string CarType_SuperTruck {
            get {
                return ResourceManager.GetString("CarType_SuperTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型车 的本地化字符串。
        /// </summary>
        internal static string CarType_Truck {
            get {
                return ResourceManager.GetString("CarType_Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理中心 的本地化字符串。
        /// </summary>
        internal static string DefaultWorkstation {
            get {
                return ResourceManager.GetString("DefaultWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不在线 的本地化字符串。
        /// </summary>
        internal static string EnSatus_OffLine {
            get {
                return ResourceManager.GetString("EnSatus_OffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡纸/塞卡 的本地化字符串。
        /// </summary>
        internal static string EnStatus_CardJam {
            get {
                return ResourceManager.GetString("EnStatus_CardJam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 故障 的本地化字符串。
        /// </summary>
        internal static string EnStatus_Error {
            get {
                return ResourceManager.GetString("EnStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 落闸到位 的本地化字符串。
        /// </summary>
        internal static string EnStatus_GateDown {
            get {
                return ResourceManager.GetString("EnStatus_GateDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抬闸到位 的本地化字符串。
        /// </summary>
        internal static string EnStatus_GateUp {
            get {
                return ResourceManager.GetString("EnStatus_GateUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡数量少 的本地化字符串。
        /// </summary>
        internal static string EnStatus_LessCard {
            get {
                return ResourceManager.GetString("EnStatus_LessCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发卡机缺卡/打印机缺纸 的本地化字符串。
        /// </summary>
        internal static string EnStatus_NoCard {
            get {
                return ResourceManager.GetString("EnStatus_NoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string EnStatus_OK {
            get {
                return ResourceManager.GetString("EnStatus_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储空间达到警界值 的本地化字符串。
        /// </summary>
        internal static string EnStatus_StorageAlarm {
            get {
                return ResourceManager.GetString("EnStatus_StorageAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储空间满 的本地化字符串。
        /// </summary>
        internal static string EnStatus_StorageFull {
            get {
                return ResourceManager.GetString("EnStatus_StorageFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAN总线停车场控制板 的本地化字符串。
        /// </summary>
        internal static string EntranceDeviceType_CAN {
            get {
                return ResourceManager.GetString("EntranceDeviceType_CAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络型停车场控制板 的本地化字符串。
        /// </summary>
        internal static string EntranceDeviceType_NET {
            get {
                return ResourceManager.GetString("EntranceDeviceType_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时 的本地化字符串。
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额不足 的本地化字符串。
        /// </summary>
        internal static string INV_Balance {
            get {
                return ResourceManager.GetString("INV_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡已注销 的本地化字符串。
        /// </summary>
        internal static string INV_Cancelled {
            get {
                return ResourceManager.GetString("INV_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌识别失败 的本地化字符串。
        /// </summary>
        internal static string INV_CarPlateWrong {
            get {
                return ResourceManager.GetString("INV_CarPlateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已缴费，但车牌不相符 的本地化字符串。
        /// </summary>
        internal static string INV_CarPlateWrongWithPaid {
            get {
                return ResourceManager.GetString("INV_CarPlateWrongWithPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片数据校验错误 的本地化字符串。
        /// </summary>
        internal static string INV_DataError {
            get {
                return ResourceManager.GetString("INV_DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许进出嵌套车场 的本地化字符串。
        /// </summary>
        internal static string INV_DisableNestedPark {
            get {
                return ResourceManager.GetString("INV_DisableNestedPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用临时卡 的本地化字符串。
        /// </summary>
        internal static string INV_ForbidTempCard {
            get {
                return ResourceManager.GetString("INV_ForbidTempCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡已在场 的本地化字符串。
        /// </summary>
        internal static string INV_HaveIn {
            get {
                return ResourceManager.GetString("INV_HaveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节假日不允许进出 的本地化字符串。
        /// </summary>
        internal static string INV_HolidayDisabled {
            get {
                return ResourceManager.GetString("INV_HolidayDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请插卡回收 的本地化字符串。
        /// </summary>
        internal static string INV_InsertToRecovery {
            get {
                return ResourceManager.GetString("INV_InsertToRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效卡片 的本地化字符串。
        /// </summary>
        internal static string INV_Invalid {
            get {
                return ResourceManager.GetString("INV_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像对比失败 的本地化字符串。
        /// </summary>
        internal static string INV_InvalidImg {
            get {
                return ResourceManager.GetString("INV_InvalidImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡已锁定 的本地化字符串。
        /// </summary>
        internal static string INV_Lock {
            get {
                return ResourceManager.GetString("INV_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡已挂失 的本地化字符串。
        /// </summary>
        internal static string INV_Loss {
            get {
                return ResourceManager.GetString("INV_Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限不足 的本地化字符串。
        /// </summary>
        internal static string INV_NoAccessRight {
            get {
                return ResourceManager.GetString("INV_NoAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到车型 的本地化字符串。
        /// </summary>
        internal static string INV_NoCarType {
            get {
                return ResourceManager.GetString("INV_NoCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片未到生效期 的本地化字符串。
        /// </summary>
        internal static string INV_NotActive {
            get {
                return ResourceManager.GetString("INV_NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置停车费率 的本地化字符串。
        /// </summary>
        internal static string INV_NoTariff {
            get {
                return ResourceManager.GetString("INV_NoTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡已过期 的本地化字符串。
        /// </summary>
        internal static string INV_OverDate {
            get {
                return ResourceManager.GetString("INV_OverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滞留超时，请重新缴费 的本地化字符串。
        /// </summary>
        internal static string INV_OverTime {
            get {
                return ResourceManager.GetString("INV_OverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车位已满 的本地化字符串。
        /// </summary>
        internal static string INV_ParkFull {
            get {
                return ResourceManager.GetString("INV_ParkFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车场编号不符 的本地化字符串。
        /// </summary>
        internal static string INV_ParkNumError {
            get {
                return ResourceManager.GetString("INV_ParkNumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请继续读卡 的本地化字符串。
        /// </summary>
        internal static string INV_ReadCard {
            get {
                return ResourceManager.GetString("INV_ReadCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡已注销 的本地化字符串。
        /// </summary>
        internal static string INV_Recycled {
            get {
                return ResourceManager.GetString("INV_Recycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡已出场 的本地化字符串。
        /// </summary>
        internal static string INV_StillOut {
            get {
                return ResourceManager.GetString("INV_StillOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片类型不符 的本地化字符串。
        /// </summary>
        internal static string INV_Type {
            get {
                return ResourceManager.GetString("INV_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string INV_Unknow {
            get {
                return ResourceManager.GetString("INV_Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此卡未登记 的本地化字符串。
        /// </summary>
        internal static string INV_UnRegister {
            get {
                return ResourceManager.GetString("INV_UnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片版本不符 的本地化字符串。
        /// </summary>
        internal static string INV_VersionError {
            get {
                return ResourceManager.GetString("INV_VersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入场时间晚于出场时间 的本地化字符串。
        /// </summary>
        internal static string INV_WrongInTime {
            get {
                return ResourceManager.GetString("INV_WrongInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缴费时间晚于出场时间 的本地化字符串。
        /// </summary>
        internal static string INV_WrongPaidTime {
            get {
                return ResourceManager.GetString("INV_WrongPaidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的小时数 的本地化字符串。
        /// </summary>
        internal static string InvalidHour {
            get {
                return ResourceManager.GetString("InvalidHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的分钟数 的本地化字符串。
        /// </summary>
        internal static string InvalidMinute {
            get {
                return ResourceManager.GetString("InvalidMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小数点位数不能小于0或者大于2 的本地化字符串。
        /// </summary>
        internal static string InvalidPointCount {
            get {
                return ResourceManager.GetString("InvalidPointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有缴费 的本地化字符串。
        /// </summary>
        internal static string IVN_NotPaid {
            get {
                return ResourceManager.GetString("IVN_NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用作临时卡收费 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_AsTempCard {
            get {
                return ResourceManager.GetString("ParkingStatus_AsTempCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区内消费优惠 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_Consume {
            get {
                return ResourceManager.GetString("ParkingStatus_Consume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已入场 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_In {
            get {
                return ResourceManager.GetString("ParkingStatus_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已入内车场 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_IndoorIn {
            get {
                return ResourceManager.GetString("ParkingStatus_IndoorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记为室内停车 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_NestedParkMarked {
            get {
                return ResourceManager.GetString("ParkingStatus_NestedParkMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已出场 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_Out {
            get {
                return ResourceManager.GetString("ParkingStatus_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已交费 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_PaidBill {
            get {
                return ResourceManager.GetString("ParkingStatus_PaidBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复入场 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_RepeatIn {
            get {
                return ResourceManager.GetString("ParkingStatus_RepeatIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复出场 的本地化字符串。
        /// </summary>
        internal static string ParkingStatus_RepeatOut {
            get {
                return ResourceManager.GetString("ParkingStatus_RepeatOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脱机模式 的本地化字符串。
        /// </summary>
        internal static string ParkWorkmode_Offline {
            get {
                return ResourceManager.GetString("ParkWorkmode_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线模式 的本地化字符串。
        /// </summary>
        internal static string ParkWorkmode_Online {
            get {
                return ResourceManager.GetString("ParkWorkmode_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金 的本地化字符串。
        /// </summary>
        internal static string PaymentMode_Cash {
            get {
                return ResourceManager.GetString("PaymentMode_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POS收费 的本地化字符串。
        /// </summary>
        internal static string PaymentMode_Pos {
            get {
                return ResourceManager.GetString("PaymentMode_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 储值卡扣款 的本地化字符串。
        /// </summary>
        internal static string PaymentMode_Prepay {
            get {
                return ResourceManager.GetString("PaymentMode_Prepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市通 的本地化字符串。
        /// </summary>
        internal static string PaymentMode_YangChengTong {
            get {
                return ResourceManager.GetString("PaymentMode_YangChengTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中山通 的本地化字符串。
        /// </summary>
        internal static string PaymentMode_ZhongShanTong {
            get {
                return ResourceManager.GetString("PaymentMode_ZhongShanTong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量发卡 的本地化字符串。
        /// </summary>
        internal static string Permission_AddCard {
            get {
                return ResourceManager.GetString("Permission_AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发管理卡 的本地化字符串。
        /// </summary>
        internal static string Permission_AddManageCard {
            get {
                return ResourceManager.GetString("Permission_AddManageCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警信息报表 的本地化字符串。
        /// </summary>
        internal static string Permission_AlarmReport {
            get {
                return ResourceManager.GetString("Permission_AlarmReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量修改卡片 的本地化字符串。
        /// </summary>
        internal static string Permission_BulkChangeCards {
            get {
                return ResourceManager.GetString("Permission_BulkChangeCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片充值报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardChargeReport {
            get {
                return ResourceManager.GetString("Permission_CardChargeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据转换 的本地化字符串。
        /// </summary>
        internal static string Permission_CardDataConvert {
            get {
                return ResourceManager.GetString("Permission_CardDataConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片延期报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardDeferReport {
            get {
                return ResourceManager.GetString("Permission_CardDeferReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月租卡收费统计 的本地化字符串。
        /// </summary>
        internal static string Permission_CardDeferStatistic {
            get {
                return ResourceManager.GetString("Permission_CardDeferStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片删除报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardDeleteReport {
            get {
                return ResourceManager.GetString("Permission_CardDeleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片禁用启用报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardDisableEnableReport {
            get {
                return ResourceManager.GetString("Permission_CardDisableEnableReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆进出报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardEventReport {
            get {
                return ResourceManager.GetString("Permission_CardEventReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡号转换 的本地化字符串。
        /// </summary>
        internal static string Permission_CardIDConvert {
            get {
                return ResourceManager.GetString("Permission_CardIDConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在场卡片查询 的本地化字符串。
        /// </summary>
        internal static string Permission_CardInParkReport {
            get {
                return ResourceManager.GetString("Permission_CardInParkReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片挂失恢复报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardLossRestoreReport {
            get {
                return ResourceManager.GetString("Permission_CardLossRestoreReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片收费管理 的本地化字符串。
        /// </summary>
        internal static string Permission_CardPaying {
            get {
                return ResourceManager.GetString("Permission_CardPaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停车收费明细报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardPayingReport {
            get {
                return ResourceManager.GetString("Permission_CardPayingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停车收费统计 的本地化字符串。
        /// </summary>
        internal static string Permission_CardPayingStatistic {
            get {
                return ResourceManager.GetString("Permission_CardPayingStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片回收报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardRecycleReport {
            get {
                return ResourceManager.GetString("Permission_CardRecycleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片发行报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CardReleaseReport {
            get {
                return ResourceManager.GetString("Permission_CardReleaseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车流量统计报表 的本地化字符串。
        /// </summary>
        internal static string Permission_CarFlowStatistics {
            get {
                return ResourceManager.GetString("Permission_CarFlowStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片管理权限 的本地化字符串。
        /// </summary>
        internal static string Permission_Catalog_Card {
            get {
                return ResourceManager.GetString("Permission_Catalog_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统数据权限 的本地化字符串。
        /// </summary>
        internal static string Permission_Catalog_Data {
            get {
                return ResourceManager.GetString("Permission_Catalog_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停车场硬件权限 的本地化字符串。
        /// </summary>
        internal static string Permission_Catalog_Hardware {
            get {
                return ResourceManager.GetString("Permission_Catalog_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表权限 的本地化字符串。
        /// </summary>
        internal static string Permission_Catalog_Report {
            get {
                return ResourceManager.GetString("Permission_Catalog_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改卡片密钥 的本地化字符串。
        /// </summary>
        internal static string Permission_ChangeCardKey {
            get {
                return ResourceManager.GetString("Permission_ChangeCardKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片充值 的本地化字符串。
        /// </summary>
        internal static string Permission_ChargeCard {
            get {
                return ResourceManager.GetString("Permission_ChargeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 落闸 的本地化字符串。
        /// </summary>
        internal static string Permission_CloseDoor {
            get {
                return ResourceManager.GetString("Permission_CloseDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片延期 的本地化字符串。
        /// </summary>
        internal static string Permission_DeferCard {
            get {
                return ResourceManager.GetString("Permission_DeferCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用卡片 的本地化字符串。
        /// </summary>
        internal static string Permission_DisableCard {
            get {
                return ResourceManager.GetString("Permission_DisableCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片全部下发 的本地化字符串。
        /// </summary>
        internal static string Permission_DownloadAllCards {
            get {
                return ResourceManager.GetString("Permission_DownloadAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑自助缴费机信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditAPM {
            get {
                return ResourceManager.GetString("Permission_EditAPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑卡片 的本地化字符串。
        /// </summary>
        internal static string Permission_EditCard {
            get {
                return ResourceManager.GetString("Permission_EditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑停车区域信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditDivision {
            get {
                return ResourceManager.GetString("Permission_EditDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑控制器信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditEntrance {
            get {
                return ResourceManager.GetString("Permission_EditEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑操作员信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditOperator {
            get {
                return ResourceManager.GetString("Permission_EditOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑停车场信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditPark {
            get {
                return ResourceManager.GetString("Permission_EditPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditRole {
            get {
                return ResourceManager.GetString("Permission_EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑系统设置 的本地化字符串。
        /// </summary>
        internal static string Permission_EditSysSetting {
            get {
                return ResourceManager.GetString("Permission_EditSysSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑摄像机信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditVideo {
            get {
                return ResourceManager.GetString("Permission_EditVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑工作站信息 的本地化字符串。
        /// </summary>
        internal static string Permission_EditWorkstation {
            get {
                return ResourceManager.GetString("Permission_EditWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用卡片 的本地化字符串。
        /// </summary>
        internal static string Permission_EnableCard {
            get {
                return ResourceManager.GetString("Permission_EnableCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出停车收费报表 的本地化字符串。
        /// </summary>
        internal static string Permission_ExportCardPayment {
            get {
                return ResourceManager.GetString("Permission_ExportCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出卡片 的本地化字符串。
        /// </summary>
        internal static string Permission_ExportCards {
            get {
                return ResourceManager.GetString("Permission_ExportCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出卡片收费报表 的本地化字符串。
        /// </summary>
        internal static string Permission_ExportMonthCardPaymentReport {
            get {
                return ResourceManager.GetString("Permission_ExportMonthCardPaymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片挂失 的本地化字符串。
        /// </summary>
        internal static string Permission_LostCard {
            get {
                return ResourceManager.GetString("Permission_LostCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改卡片收费记录 的本地化字符串。
        /// </summary>
        internal static string Permission_ModifyCardPaymentRecord {
            get {
                return ResourceManager.GetString("Permission_ModifyCardPaymentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抬闸 的本地化字符串。
        /// </summary>
        internal static string Permission_OpenDoor {
            get {
                return ResourceManager.GetString("Permission_OpenDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员结算 的本地化字符串。
        /// </summary>
        internal static string Permission_OperatorSettle {
            get {
                return ResourceManager.GetString("Permission_OperatorSettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员交接班报表 的本地化字符串。
        /// </summary>
        internal static string Permission_OperatorShiftStatistics {
            get {
                return ResourceManager.GetString("Permission_OperatorShiftStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对其它操作员结算 的本地化字符串。
        /// </summary>
        internal static string Permission_OtherOperatorSettle {
            get {
                return ResourceManager.GetString("Permission_OtherOperatorSettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自助缴费机日志查询 的本地化字符串。
        /// </summary>
        internal static string Permission_PayOperationLogReport {
            get {
                return ResourceManager.GetString("Permission_PayOperationLogReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印停车收费报表 的本地化字符串。
        /// </summary>
        internal static string Permission_PrintCardPayment {
            get {
                return ResourceManager.GetString("Permission_PrintCardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印卡片收费报表 的本地化字符串。
        /// </summary>
        internal static string Permission_PrintMonthCardPaymentReport {
            get {
                return ResourceManager.GetString("Permission_PrintMonthCardPaymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印操作员结算单 的本地化字符串。
        /// </summary>
        internal static string Permission_PrintOperatorSettleLog {
            get {
                return ResourceManager.GetString("Permission_PrintOperatorSettleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取自助缴费机信息 的本地化字符串。
        /// </summary>
        internal static string Permission_ReadAPM {
            get {
                return ResourceManager.GetString("Permission_ReadAPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看卡片 的本地化字符串。
        /// </summary>
        internal static string Permission_ReadCard {
            get {
                return ResourceManager.GetString("Permission_ReadCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看操作员信息 的本地化字符串。
        /// </summary>
        internal static string Permission_ReadOperator {
            get {
                return ResourceManager.GetString("Permission_ReadOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看角色信息 的本地化字符串。
        /// </summary>
        internal static string Permission_ReadRole {
            get {
                return ResourceManager.GetString("Permission_ReadRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看系统设置 的本地化字符串。
        /// </summary>
        internal static string Permission_ReadSysSetting {
            get {
                return ResourceManager.GetString("Permission_ReadSysSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看工作站信息 的本地化字符串。
        /// </summary>
        internal static string Permission_ReadWorkstation {
            get {
                return ResourceManager.GetString("Permission_ReadWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看实时事件 的本地化字符串。
        /// </summary>
        internal static string Permission_RealEvent {
            get {
                return ResourceManager.GetString("Permission_RealEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回收卡片 的本地化字符串。
        /// </summary>
        internal static string Permission_RecycleCard {
            get {
                return ResourceManager.GetString("Permission_RecycleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片发行 的本地化字符串。
        /// </summary>
        internal static string Permission_ReleaseCard {
            get {
                return ResourceManager.GetString("Permission_ReleaseCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程读卡 的本地化字符串。
        /// </summary>
        internal static string Permission_RemoteReadCard {
            get {
                return ResourceManager.GetString("Permission_RemoteReadCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器复位 的本地化字符串。
        /// </summary>
        internal static string Permission_ResetDevice {
            get {
                return ResourceManager.GetString("Permission_ResetDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片恢复 的本地化字符串。
        /// </summary>
        internal static string Permission_RestoreCard {
            get {
                return ResourceManager.GetString("Permission_RestoreCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步数据到备用数据库 的本地化字符串。
        /// </summary>
        internal static string Permission_SyncDataToStandby {
            get {
                return ResourceManager.GetString("Permission_SyncDataToStandby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前工作站设置 的本地化字符串。
        /// </summary>
        internal static string Permission_SystemIDSetting {
            get {
                return ResourceManager.GetString("Permission_SystemIDSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置临时卡数量 的本地化字符串。
        /// </summary>
        internal static string Permission_TempCardSetting {
            get {
                return ResourceManager.GetString("Permission_TempCardSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时视频 的本地化字符串。
        /// </summary>
        internal static string Permission_VideoMonitor {
            get {
                return ResourceManager.GetString("Permission_VideoMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 羊城通扣费记录查询 的本地化字符串。
        /// </summary>
        internal static string Permission_YangChenTongLogReport {
            get {
                return ResourceManager.GetString("Permission_YangChenTongLogReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中山通设置 的本地化字符串。
        /// </summary>
        internal static string Permission_ZSTSeting {
            get {
                return ResourceManager.GetString("Permission_ZSTSeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机串口未打开 的本地化字符串。
        /// </summary>
        internal static string PrinterStatus_COMPortNotOpen {
            get {
                return ResourceManager.GetString("PrinterStatus_COMPortNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机断开 的本地化字符串。
        /// </summary>
        internal static string PrinterStatus_OffLine {
            get {
                return ResourceManager.GetString("PrinterStatus_OffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string PrinterStatus_Ok {
            get {
                return ResourceManager.GetString("PrinterStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印机缺纸 的本地化字符串。
        /// </summary>
        internal static string PrinterStatus_PaperAbsent {
            get {
                return ResourceManager.GetString("PrinterStatus_PaperAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string PrinterStatus_Unknown {
            get {
                return ResourceManager.GetString("PrinterStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余额 的本地化字符串。
        /// </summary>
        internal static string Report_Balance {
            get {
                return ResourceManager.GetString("Report_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆到达 的本地化字符串。
        /// </summary>
        internal static string Report_CarArrived {
            get {
                return ResourceManager.GetString("Report_CarArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下取卡按钮 的本地化字符串。
        /// </summary>
        internal static string Report_CardButton {
            get {
                return ResourceManager.GetString("Report_CardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收卡一张 的本地化字符串。
        /// </summary>
        internal static string Report_CardCapture {
            get {
                return ResourceManager.GetString("Report_CardCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读卡事件 卡号 的本地化字符串。
        /// </summary>
        internal static string Report_CardRead {
            get {
                return ResourceManager.GetString("Report_CardRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车辆离开 的本地化字符串。
        /// </summary>
        internal static string Report_CarLeave {
            get {
                return ResourceManager.GetString("Report_CarLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车牌号 的本地化字符串。
        /// </summary>
        internal static string Report_CarPlate {
            get {
                return ResourceManager.GetString("Report_CarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷卡抬闸成功 的本地化字符串。
        /// </summary>
        internal static string Report_CommandEcho {
            get {
                return ResourceManager.GetString("Report_CommandEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复位 的本地化字符串。
        /// </summary>
        internal static string Report_DeviceReset {
            get {
                return ResourceManager.GetString("Report_DeviceReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入场 的本地化字符串。
        /// </summary>
        internal static string Report_Enter {
            get {
                return ResourceManager.GetString("Report_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求入场 的本地化字符串。
        /// </summary>
        internal static string Report_EnterRequest {
            get {
                return ResourceManager.GetString("Report_EnterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出场 的本地化字符串。
        /// </summary>
        internal static string Report_Exit {
            get {
                return ResourceManager.GetString("Report_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求出场 的本地化字符串。
        /// </summary>
        internal static string Report_ExitRequest {
            get {
                return ResourceManager.GetString("Report_ExitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入场车牌号 的本地化字符串。
        /// </summary>
        internal static string Report_LastCarPlate {
            get {
                return ResourceManager.GetString("Report_LastCarPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脱机卡片有效 的本地化字符串。
        /// </summary>
        internal static string Report_OfflineCardPermitted {
            get {
                return ResourceManager.GetString("Report_OfflineCardPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脱机卡片等待 的本地化字符串。
        /// </summary>
        internal static string Report_OfflineCardWait {
            get {
                return ResourceManager.GetString("Report_OfflineCardWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余车位数 的本地化字符串。
        /// </summary>
        internal static string Report_ParkVacant {
            get {
                return ResourceManager.GetString("Report_ParkVacant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接数据库失败 的本地化字符串。
        /// </summary>
        internal static string ResultCode_CannotConnectServer {
            get {
                return ResourceManager.GetString("ResultCode_CannotConnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string ResultCode_Fail {
            get {
                return ResourceManager.GetString("ResultCode_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到记录 的本地化字符串。
        /// </summary>
        internal static string ResultCode_NoRecord {
            get {
                return ResourceManager.GetString("ResultCode_NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据写入数据库时失败 的本地化字符串。
        /// </summary>
        internal static string ResultCode_SaveDataError {
            get {
                return ResourceManager.GetString("ResultCode_SaveDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string ResultCode_Successfull {
            get {
                return ResourceManager.GetString("ResultCode_Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时段限额收费 的本地化字符串。
        /// </summary>
        internal static string Tariff_Dixiakongjian {
            get {
                return ResourceManager.GetString("Tariff_Dixiakongjian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日夜差异收费 的本地化字符串。
        /// </summary>
        internal static string Tariff_Guanzhou {
            get {
                return ResourceManager.GetString("Tariff_Guanzhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限额收费 的本地化字符串。
        /// </summary>
        internal static string Tariff_Limitation {
            get {
                return ResourceManager.GetString("Tariff_Limitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过零点收费 的本地化字符串。
        /// </summary>
        internal static string Tariff_MidLight {
            get {
                return ResourceManager.GetString("Tariff_MidLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按天收费 的本地化字符串。
        /// </summary>
        internal static string Tariff_PerDay {
            get {
                return ResourceManager.GetString("Tariff_PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按次收费 的本地化字符串。
        /// </summary>
        internal static string Tariff_PerTime {
            get {
                return ResourceManager.GetString("Tariff_PerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过点收费 的本地化字符串。
        /// </summary>
        internal static string Tariff_Turning {
            get {
                return ResourceManager.GetString("Tariff_Turning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节假日收费 的本地化字符串。
        /// </summary>
        internal static string TariffType_Holiday {
            get {
                return ResourceManager.GetString("TariffType_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节假日室内收费 的本地化字符串。
        /// </summary>
        internal static string TariffType_HolidayAndInnerRoom {
            get {
                return ResourceManager.GetString("TariffType_HolidayAndInnerRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 室内收费 的本地化字符串。
        /// </summary>
        internal static string TariffType_InnerRoom {
            get {
                return ResourceManager.GetString("TariffType_InnerRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通收费 的本地化字符串。
        /// </summary>
        internal static string TariffType_Normal {
            get {
                return ResourceManager.GetString("TariffType_Normal", resourceCulture);
            }
        }
    }
}
